global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']

  - job_name: otel-collector
    metrics_path: /metrics
    static_configs:
      - targets: ['otel-collector:8888']

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'cumulus-snmp-interfaces'
    metrics_path: /snmp
    params:
      module: [if_mib]
      auth: [cumulus_v3]
    static_configs:
      - targets:
          - SNMP_DEVICE_1_IP
          - SNMP_DEVICE_2_IP
          - SNMP_DEVICE_3_IP
          - SNMP_DEVICE_4_IP
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116

  - job_name: 'cumulus-snmp-lldp'
    metrics_path: /snmp
    params:
      module: [cumulus_lldp]
      auth: [cumulus_v3]
    static_configs:
      - targets:
          - SNMP_DEVICE_1_IP
          - SNMP_DEVICE_2_IP
          - SNMP_DEVICE_3_IP
          - SNMP_DEVICE_4_IP
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116

rule_files:
  - /etc/prometheus/rules/*.yml
